# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='modify_time',
            new_name='last_modify_time',
        ),
    ]
